version: '3.9'
services: 
  backend:
    build: .
    command: 'python3.9 main.py'
    ports: 
      - 8001:5000
    volumes: 
      - .:/app
    depends_on: 
      - db

  queue:
    build:
      context: .
    command: 'python3.9 consumer.py'
    depends_on: 
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db
    volumes: 
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports: 
      - "5433:5432"
